name: Safety SCA Scan

on: [push, pull_request]

jobs:
  oast-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Safety
        run: pip install safety

      - name: Execute Software Composition Analysis
        continue-on-error: true
        run: safety scan
